/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bc.tasktracker.client.ui;

import com.bc.appbase.ui.DatePanel;
import com.bc.appbase.ui.DateUIUpdater;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import com.bc.tasktracker.client.ui.actions.TasktrackerActionCommands;
import com.bc.tasktracker.client.TasktrackerApp;

/**
 * @author Josh
 */
public class SearchPanel extends javax.swing.JPanel {

    public SearchPanel() {
        this(null);
    }
    
    public SearchPanel(TasktrackerApp app) {
        initComponents();
        if(app != null) {
            this.init(app);
        }
    }

    public void init(TasktrackerApp app) {
        
        final String [] values = app.getAppointmentNames();
        
        this.getResponsiblityCombobox().setModel(new DefaultComboBoxModel<>(values));
        
        final ActionListener actionListener = app.getUIContext().getActionListener(this, TasktrackerActionCommands.SEARCH_AND_DISPLAY_RESULTS_UI);
        this.getSearchTextfield().setActionCommand(TasktrackerActionCommands.SEARCH_AND_DISPLAY_RESULTS_UI);
        this.getSearchTextfield().addActionListener(actionListener);
        this.getSearchButton().setActionCommand(TasktrackerActionCommands.SEARCH_AND_DISPLAY_RESULTS_UI);
        this.getSearchButton().addActionListener(actionListener);
        
        this.setToDefaults(app);
    }
    
    public void reset(TasktrackerApp app) {
        
        this.getResponsiblityCombobox().setSelectedIndex(0);
        
        this.getSearchTextfield().setText(null);
        
        this.getClosedTasksCheckBox().setSelected(false);
        
        DatePanel dateTimePanel = this.getFromDateTimePanel();
        dateTimePanel.getDayTextfield().setText(null);
        
        this.setToDefaults(app);
    }
    
    public void setToDefaults(TasktrackerApp app) {
        
        final DateUIUpdater updater = app.getOrException(DateUIUpdater.class);
        
        final Calendar cal = app.getCalendar();
        
        final DatePanel fromDatePanel = this.getFromDateTimePanel();
        
        updater.updateMonth(fromDatePanel.getMonthCombobox(), cal);
        updater.updateYear(fromDatePanel.getYearCombobox(), cal);
        
//        updater.updateField(container.getToDateTimePanel().getDayTextfield(), cal, Calendar.DAY_OF_MONTH);
        updater.updateMonth(this.getToDateTimePanel().getMonthCombobox(), cal);
        updater.updateYear(this.getToDateTimePanel().getYearCombobox(), cal);

/////////////////

        updater.updateMonth(this.getFromDeadlineDateTimePanel().getMonthCombobox(), cal);
        updater.updateYear(this.getFromDeadlineDateTimePanel().getYearCombobox(), cal);
        
//        updater.updateField(container.getToDeadlineDateTimePanel().getDayTextfield(), cal, Calendar.DAY_OF_MONTH);
        updater.updateMonth(this.getToDeadlineDateTimePanel().getMonthCombobox(), cal);
        updater.updateYear(this.getToDeadlineDateTimePanel().getYearCombobox(), cal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextfield = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        closedTasksCheckBox = new javax.swing.JCheckBox();
        responsibilityLabel = new javax.swing.JLabel();
        responsiblityCombobox = new javax.swing.JComboBox<>();
        periodLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        deadlineLabel = new javax.swing.JLabel();
        fromDateTimePanel = new com.bc.appbase.ui.DatePanel();
        toDateTimePanel = new com.bc.appbase.ui.DatePanel();
        fromDeadlineDateTimePanel = new com.bc.appbase.ui.DatePanel();
        toDeadlineDateTimePanel = new com.bc.appbase.ui.DatePanel();

        setPreferredSize(new java.awt.Dimension(805, 235));

        searchTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fromLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fromLabel.setText("From");
        fromLabel.setToolTipText("Time tracking begins. You may set this later.");

        toLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toLabel.setText("To");

        closedTasksCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closedTasksCheckBox.setText("Closed Tasks");

        responsibilityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        responsibilityLabel.setText("Who");

        responsiblityCombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        responsiblityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        periodLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodLabel.setText("Track Start");

        deadlineLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deadlineLabel.setText("Deadline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(responsiblityCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closedTasksCheckBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(periodLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fromLabel)
                                    .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toDeadlineDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deadlineLabel)
                                            .addComponent(fromDeadlineDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(responsiblityCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closedTasksCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodLabel)
                    .addComponent(deadlineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromLabel)
                        .addGap(18, 18, 18)
                        .addComponent(toLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromDeadlineDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toDeadlineDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox closedTasksCheckBox;
    private javax.swing.JLabel deadlineLabel;
    private com.bc.appbase.ui.DatePanel fromDateTimePanel;
    private com.bc.appbase.ui.DatePanel fromDeadlineDateTimePanel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JLabel responsibilityLabel;
    private javax.swing.JComboBox<String> responsiblityCombobox;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextfield;
    private javax.swing.JSeparator separator;
    private com.bc.appbase.ui.DatePanel toDateTimePanel;
    private com.bc.appbase.ui.DatePanel toDeadlineDateTimePanel;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getSearchButton() {
        return searchButton;
    }

    public JTextField getSearchTextfield() {
        return searchTextfield;
    }

    public JLabel getFromLabel() {
        return fromLabel;
    }

    public JLabel getToLabel() {
        return toLabel;
    }

    public JCheckBox getClosedTasksCheckBox() {
        return closedTasksCheckBox;
    }

    public JLabel getDeadlineLabel() {
        return deadlineLabel;
    }

    public JLabel getPeriodLabel() {
        return periodLabel;
    }

    public JLabel getResponsibilityLabel() {
        return responsibilityLabel;
    }

    public JComboBox<String> getResponsiblityCombobox() {
        return responsiblityCombobox;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public DatePanel getFromDateTimePanel() {
        return fromDateTimePanel;
    }

    public DatePanel getFromDeadlineDateTimePanel() {
        return fromDeadlineDateTimePanel;
    }

    public DatePanel getToDateTimePanel() {
        return toDateTimePanel;
    }

    public DatePanel getToDeadlineDateTimePanel() {
        return toDeadlineDateTimePanel;
    }
}
