/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bc.tasktracker.client.ui;

import com.bc.appbase.ui.DatePanel;
import com.bc.appbase.ui.DateUIUpdater;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import com.bc.tasktracker.client.ui.actions.TasktrackerActionCommands;
import com.bc.tasktracker.client.TasktrackerApp;

/**
 * @author Josh
 */
public class TaskPanel extends javax.swing.JPanel {

    public TaskPanel() {
        this(null);
    }
    
    public TaskPanel(TasktrackerApp app) {
        initComponents();
        if(app != null) {
            this.init(app);
        }
    }

    public void reset(TasktrackerApp app) {
        this.setToDefaults(app);
    }
    
    public void init(TasktrackerApp app) {

        final String [] values = app.getAppointmentNames();
        
        this.getResponsiblityCombobox().setModel(new DefaultComboBoxModel<>(values));
        
        this.getAddTaskAndDocButton().setActionCommand(TasktrackerActionCommands.ADD_TASK_AND_DOC);
        this.getAddTaskToDocButton().setActionCommand(TasktrackerActionCommands.ADD_TASK_TO_DOC);
        this.getCleartaskButton().setActionCommand(TasktrackerActionCommands.CLEAR_TASK);
        
        app.getUIContext().addActionListeners(
                this,
                this.getAddTaskAndDocButton(), 
                this.getAddTaskToDocButton(),
                this.getCleartaskButton());
        
        this.setToDefaults(app);
    }
    
    public void setToDefaults(TasktrackerApp app) {
        
        this.getDocidLabel().setText("DOC ID");
        this.getReferencenumberTextfield().setText(null);
        this.getSubjectTextfield().setText(null);
        this.getTaskTextArea().setText(null);
        
        this.getResponsiblityCombobox().setSelectedIndex(0);
        
        final DateUIUpdater updater = app.getOrException(DateUIUpdater.class);
        
        final Calendar cal = app.getCalendar();
        
        final DatePanel datesingedDp = this.getDatesignedDatePanel();
//        updater.updateField(datePanel.getDayTextfield(), cal, Calendar.DAY_OF_MONTH);
        datesingedDp.getDayTextfield().setText(null);
        updater.updateMonth(datesingedDp.getMonthCombobox(), cal);
        updater.updateYear(datesingedDp.getYearCombobox(), cal);
        
        final DatePanel timeopenedDp = this.getTimeopenedDatePanel();
//        updater.updateField(timeopenedDp.getHoursTextfield(), cal, Calendar.HOUR_OF_DAY);
//        updater.updateField(timeopenedDp.getMinutesTextfield(), cal, Calendar.MINUTE);
        
//        updater.updateField(timeopenedDp.getDayTextfield(), cal, Calendar.DAY_OF_MONTH);
        timeopenedDp.getDayTextfield().setText(null);
        updater.updateMonth(timeopenedDp.getMonthCombobox(), cal);
        updater.updateYear(timeopenedDp.getYearCombobox(), cal);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        referencenumberLabel = new javax.swing.JLabel();
        referencenumberTextfield = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        subjectTextfield = new javax.swing.JTextField();
        taskLabel = new javax.swing.JLabel();
        responsibilityLabel = new javax.swing.JLabel();
        responsiblityCombobox = new javax.swing.JComboBox<>();
        timeopendLabel = new javax.swing.JLabel();
        addTaskAndDocButton = new javax.swing.JButton();
        cleartaskButton = new javax.swing.JButton();
        formNoteLabel = new javax.swing.JLabel();
        addTaskToDocButton = new javax.swing.JButton();
        docidLabel = new javax.swing.JLabel();
        datesignedLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        taskdetailsLabel = new javax.swing.JLabel();
        taskTextAreaScrollPane = new javax.swing.JScrollPane();
        taskTextArea = new javax.swing.JTextArea();
        datesignedDatePanel = new com.bc.appbase.ui.DatePanel();
        timeopenedDatePanel = new com.bc.appbase.ui.DatePanel();

        referencenumberLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        referencenumberLabel.setText("Ref Number ");

        referencenumberTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        subjectLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subjectLabel.setText("<html><span style=\"color:red\">Subject *</span></html>     ");

        subjectTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        taskLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskLabel.setText("<html><span style=\"color:red\">Task *</span></html>");

        responsibilityLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        responsibilityLabel.setText("<html><span style=\"color:red\">Who *</span></html>");

        responsiblityCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        responsiblityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeopendLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopendLabel.setText("Track Starts");
        timeopendLabel.setToolTipText("Time tracking begins. You may set this later.");

        addTaskAndDocButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addTaskAndDocButton.setText("Add Task");
        addTaskAndDocButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cleartaskButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cleartaskButton.setText("Clear");
        cleartaskButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        formNoteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formNoteLabel.setText("<html>Asterixed (<span style=\"color:red\">*</span>) fields are mandatory</html>");

        addTaskToDocButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addTaskToDocButton.setText(">>");
        addTaskToDocButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        docidLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        docidLabel.setText("DOC ID");

        datesignedLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        datesignedLabel.setText("Date Signed");
        datesignedLabel.setToolTipText("Time tracking begins. You may set this later.");

        taskdetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taskdetailsLabel.setText("Task Details");

        taskTextArea.setColumns(20);
        taskTextArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        taskTextArea.setRows(5);
        taskTextAreaScrollPane.setViewportView(taskTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(referencenumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectTextfield)
                            .addComponent(referencenumberTextfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docidLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskTextAreaScrollPane)
                            .addComponent(responsiblityCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datesignedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datesignedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeopendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timeopenedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addTaskAndDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addTaskToDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cleartaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(taskdetailsLabel)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(docidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(referencenumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencenumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datesignedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datesignedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskdetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(taskTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsiblityCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timeopendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeopenedDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTaskAndDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTaskToDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleartaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskAndDocButton;
    private javax.swing.JButton addTaskToDocButton;
    private javax.swing.JButton cleartaskButton;
    private com.bc.appbase.ui.DatePanel datesignedDatePanel;
    private javax.swing.JLabel datesignedLabel;
    private javax.swing.JLabel docidLabel;
    private javax.swing.JLabel formNoteLabel;
    private javax.swing.JLabel referencenumberLabel;
    private javax.swing.JTextField referencenumberTextfield;
    private javax.swing.JLabel responsibilityLabel;
    private javax.swing.JComboBox<String> responsiblityCombobox;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTextfield;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JTextArea taskTextArea;
    private javax.swing.JScrollPane taskTextAreaScrollPane;
    private javax.swing.JLabel taskdetailsLabel;
    private javax.swing.JLabel timeopendLabel;
    private com.bc.appbase.ui.DatePanel timeopenedDatePanel;
    // End of variables declaration//GEN-END:variables

    public JButton getAddTaskAndDocButton() {
        return addTaskAndDocButton;
    }

    public JButton getAddTaskToDocButton() {
        return addTaskToDocButton;
    }

    public JButton getCleartaskButton() {
        return cleartaskButton;
    }

    public JLabel getDocidLabel() {
        return docidLabel;
    }

    public JLabel getReferencenumberLabel() {
        return referencenumberLabel;
    }

    public JTextField getReferencenumberTextfield() {
        return referencenumberTextfield;
    }

    public JLabel getResponsibilityLabel() {
        return responsibilityLabel;
    }

    public JComboBox<String> getResponsiblityCombobox() {
        return responsiblityCombobox;
    }

    public JLabel getSubjectLabel() {
        return subjectLabel;
    }

    public JTextField getSubjectTextfield() {
        return subjectTextfield;
    }

    public JLabel getTaskLabel() {
        return taskLabel;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public JTextArea getTaskTextArea() {
        return taskTextArea;
    }

    public JLabel getTaskdetailsLabel() {
        return taskdetailsLabel;
    }

    public JLabel getTimeopendLabel() {
        return timeopendLabel;
    }

    public JLabel getFormNoteLabel() {
        return formNoteLabel;
    }

    public JLabel getDatesignedLabel() {
        return datesignedLabel;
    }

    public JScrollPane getTaskTextAreaScrollPane() {
        return taskTextAreaScrollPane;
    }

    public DatePanel getDatesignedDatePanel() {
        return datesignedDatePanel;
    }

    public DatePanel getTimeopenedDatePanel() {
        return timeopenedDatePanel;
    }
}
